server:
  tomcat:
    max-connections: 5000
    uri-encoding: UTF-8
    min-spare-threads: 30
    max-threads: 1000
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  http:
     multipart:
       max-file-size: 1024MB
       max-request-size: 1024MB
       enabled: true

mybatis-plus:
  mapper-locations: /com/hznu/fa2login/sys/**/mapper/*Mapper.xml
  type-aliases-package: com.hznu.fa2login.sys.sys.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
config:
  password:
     algorithmName: "md5"
     hashIterations: 2


